2011-09-21 18:28:59,151 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:29:14,142 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_CLUSTER_F90', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:29:14,142 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_CLUSTER_F90', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:29:14,144 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:29:14,144 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:29:14,157 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_NEIGH_RVEC_F', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:29:14,157 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_NEIGH_RVEC_F', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:29:14,157 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:29:14,157 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:29:37,293 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_CLUSTER_F90', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:29:37,293 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_CLUSTER_F90', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:29:37,299 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:29:37,299 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

