2011-09-20 00:29:55,514 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='emt', element='O', info:OverflowError('range() result has too many items',)
2011-09-20 00:29:55,516 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "/home/alemi/Dropbox/openkimtests/bin/pipeline.py", line 123, in run_tests
    verbose=verbose)
  File "/home/alemi/Dropbox/openkimtests/bin/pipeline.py", line 50, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 80, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 316, in fmin
    fxcc = func(xcc)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/home/alemi/ase/ase/atoms.py", line 494, in get_potential_energy
    return self.calc.get_potential_energy(self)
  File "/home/alemi/ase/ase/calculators/emt.py", line 135, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/ase/ase/calculators/emt.py", line 117, in update
    self.calculate(atoms)
  File "/home/alemi/ase/ase/calculators/emt.py", line 189, in calculate
    for i1 in range(-N1, N1 + 1):
OverflowError: range() result has too many items

2011-09-20 00:30:05,719 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='emt', element='O', info:OverflowError('range() result has too many items',)
2011-09-20 00:30:05,720 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "/home/alemi/Dropbox/openkimtests/bin/pipeline.py", line 123, in run_tests
    verbose=verbose)
  File "/home/alemi/Dropbox/openkimtests/bin/pipeline.py", line 50, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 80, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 316, in fmin
    fxcc = func(xcc)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/home/alemi/ase/ase/atoms.py", line 494, in get_potential_energy
    return self.calc.get_potential_energy(self)
  File "/home/alemi/ase/ase/calculators/emt.py", line 135, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/ase/ase/calculators/emt.py", line 117, in update
    self.calculate(atoms)
  File "/home/alemi/ase/ase/calculators/emt.py", line 189, in calculate
    for i1 in range(-N1, N1 + 1):
OverflowError: range() result has too many items

2011-09-20 00:30:30,669 - openkimtests.potential - WARNING - Potential 'EMT' not found
2011-09-20 00:30:41,717 - openkimtests.potential - WARNING - Potential 'EMT' not found
2011-09-20 00:31:36,920 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='emt', element='O', info:OverflowError('range() result has too many items',)
2011-09-20 00:31:36,922 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 123, in run_tests
    verbose=verbose)
  File "pipeline.py", line 50, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 80, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 316, in fmin
    fxcc = func(xcc)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/home/alemi/ase/ase/atoms.py", line 494, in get_potential_energy
    return self.calc.get_potential_energy(self)
  File "/home/alemi/ase/ase/calculators/emt.py", line 135, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/ase/ase/calculators/emt.py", line 117, in update
    self.calculate(atoms)
  File "/home/alemi/ase/ase/calculators/emt.py", line 189, in calculate
    for i1 in range(-N1, N1 + 1):
OverflowError: range() result has too many items

2011-09-20 00:32:30,352 - openkimtests.potential - WARNING - Potential 'EMT' not found
2011-09-20 00:33:49,705 - openkimtests.potential - WARNING - Potential 'EMT' not found
2011-09-20 00:54:47,433 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='EMT', element='O', info:OverflowError('range() result has too many items',)
2011-09-20 00:54:47,435 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 123, in run_tests
    verbose=verbose)
  File "pipeline.py", line 50, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 80, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 316, in fmin
    fxcc = func(xcc)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/home/alemi/ase/ase/atoms.py", line 494, in get_potential_energy
    return self.calc.get_potential_energy(self)
  File "/home/alemi/ase/ase/calculators/emt.py", line 135, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/ase/ase/calculators/emt.py", line 117, in update
    self.calculate(atoms)
  File "/home/alemi/ase/ase/calculators/emt.py", line 189, in calculate
    for i1 in range(-N1, N1 + 1):
OverflowError: range() result has too many items

2011-09-20 00:56:00,759 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='EMT', element='O', info:OverflowError('range() result has too many items',)
2011-09-20 00:56:00,763 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 123, in run_tests
    verbose=verbose)
  File "pipeline.py", line 50, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 80, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 316, in fmin
    fxcc = func(xcc)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/home/alemi/ase/ase/atoms.py", line 494, in get_potential_energy
    return self.calc.get_potential_energy(self)
  File "/home/alemi/ase/ase/calculators/emt.py", line 135, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/ase/ase/calculators/emt.py", line 117, in update
    self.calculate(atoms)
  File "/home/alemi/ase/ase/calculators/emt.py", line 189, in calculate
    for i1 in range(-N1, N1 + 1):
OverflowError: range() result has too many items

2011-09-21 17:14:27,550 - openkimtests.potential - WARNING - Potential 'model_Ar_P_MLJ_C' not found
2011-09-21 17:15:07,727 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_MI_OPBC_H_F', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 17:15:07,727 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_MI_OPBC_H_F', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 17:15:07,832 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 17:15:07,832 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 17:15:18,575 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_CLUSTER_F90', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 17:15:18,575 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_CLUSTER_F90', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 17:15:18,576 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 17:15:18,576 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 17:15:18,593 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_NEIGH_RVEC_F', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 17:15:18,593 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_NEIGH_RVEC_F', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 17:15:18,594 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 17:15:18,594 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 17:15:18,641 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_ArNe_P_MLJ_NEIGH_RVEC_F', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 17:15:18,641 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_ArNe_P_MLJ_NEIGH_RVEC_F', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 17:15:18,643 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 17:15:18,643 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 17:15:18,672 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_ArNe_P_MLJ_NEIGH_RVEC_F', element='Ne', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 17:15:18,672 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_ArNe_P_MLJ_NEIGH_RVEC_F', element='Ne', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 17:15:18,672 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 17:15:18,672 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 17:15:18,688 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_CLUSTER_C', element='Ar', info:RuntimeError('Failed to retreive any thermo_style-output',)
2011-09-21 17:15:18,688 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_CLUSTER_C', element='Ar', info:RuntimeError('Failed to retreive any thermo_style-output',)
2011-09-21 17:15:18,689 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 245, in run
    raise RuntimeError('Failed to retreive any thermo_style-output')
RuntimeError: Failed to retreive any thermo_style-output

2011-09-21 17:15:18,689 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 245, in run
    raise RuntimeError('Failed to retreive any thermo_style-output')
RuntimeError: Failed to retreive any thermo_style-output

2011-09-21 17:15:18,704 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_NEIGH_PURE_H_F', element='Ar', info:RuntimeError('Failed to retreive any thermo_style-output',)
2011-09-21 17:15:18,704 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_NEIGH_PURE_H_F', element='Ar', info:RuntimeError('Failed to retreive any thermo_style-output',)
2011-09-21 17:15:18,704 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 245, in run
    raise RuntimeError('Failed to retreive any thermo_style-output')
RuntimeError: Failed to retreive any thermo_style-output

2011-09-21 17:15:18,704 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 245, in run
    raise RuntimeError('Failed to retreive any thermo_style-output')
RuntimeError: Failed to retreive any thermo_style-output

2011-09-21 18:15:42,004 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_MI_OPBC_H_F', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:15:42,004 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_MI_OPBC_H_F', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:15:42,005 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:15:42,005 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:15:42,028 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_CLUSTER_F90', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:15:42,028 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_CLUSTER_F90', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:15:42,029 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:15:42,029 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:15:42,048 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_NEIGH_RVEC_F', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:15:42,048 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_NEIGH_RVEC_F', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:15:42,049 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:15:42,049 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:15:42,074 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_ArNe_P_MLJ_NEIGH_RVEC_F', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:15:42,074 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_ArNe_P_MLJ_NEIGH_RVEC_F', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:15:42,074 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:15:42,074 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:15:42,088 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_ArNe_P_MLJ_NEIGH_RVEC_F', element='Ne', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:15:42,088 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_ArNe_P_MLJ_NEIGH_RVEC_F', element='Ne', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:15:42,089 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:15:42,089 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:15:42,109 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_CLUSTER_C', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:15:42,109 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_CLUSTER_C', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:15:42,111 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:15:42,111 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:15:42,131 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_NEIGH_PURE_H_F', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:15:42,131 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCLattice', potential='model_Ar_P_MLJ_NEIGH_PURE_H_F', element='Ar', info:RuntimeError('LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.',)
2011-09-21 18:15:42,132 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

2011-09-21 18:15:42,132 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 257, in fmin
    fsim[0] = func(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.9.0-py2.7-linux-x86_64.egg/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/home/alemi/Dropbox/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/lib/python2.7/dist-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/home/alemi/Dropbox/openkimtests/bin/kim.py", line 241, in run
    (cwd,exitcode))
RuntimeError: LAMMPS exited in /home/alemi/Dropbox/openkimtests/tmp with exit code: 101.

